[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "demand-tools"
version = "0.2.8"
description = "Набор функций для работы с датафреймами и загрузки данных"
requires-python = ">=3.9"
readme = "README.md"
keywords = ["pandas", "data-processing"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Libraries :: Python Modules"
]
authors = [
  { name = "Dmitry Romanov" }
]
license = { text = "MIT" }
dependencies = [
    "pandas>=2.0.0",
    "tqdm>=4.66.0",
    "requests>=2.32.0"
]

[project.optional-dependencies]
dev = [
    "black>=24.0.0",
    "isort>=5.13.0",
    "radon>=7.0.0"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["dp_tools"]

